# Information for participants

## International travel

Our university travel provider, Selective, has booked your flights. A pdf with your flight itinerary has been shared via email.


## Arrival in Glasgow

Your flight will arrive at [Glasgow International Airport](https://www.glasgowairport.com/). 

## Accommodation

During the workshop (26-30th) you will stay on location at SCENE (outside of Glasgow) in single or multiple occupancy rooms. Either side of the workshop (25th June & 1st July) we will provide hotel accommodation in Glasgow city. Due to high demand during the summer months (and an Arctic Monkeys gig!) we have had to split your stay into 2 hotels, therefore the itinerary is a bit complicated: 

#### 25-26th June: [Motel One Glasgow](https://www.motel-one.com/en/hotels/glasgow/hotel-glasgow/)
Hotel in the city centre, great access to public transport (right next to Glasgow Central train station!)
#### 26-30th June: SCENE
University field station beside Loch Lomond
#### 1-2nd July: [Hotel Campanile Glasgow SECC](https://glasgow.campanile.com/en-us/)
Hotel in the west end, close to the university and good access to public transport.


